version: '3.8'

services:
  embedder:
    build: .
    ports:
      - "6006:6006"
      - "8888:8888"  # If running Jupyter
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
